// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utomgjsajzlwdqkekpjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0b21nanNhanpsd2Rxa2VrcGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjU0MTMsImV4cCI6MjA2NzMwMTQxM30.U-5BOQRb2AebTVh_2q8cv-Tua9TIkUgT9BL2Do6rgxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});